export const teacherMenu = [
  { href: "/teacher", labelKey: "nav.teacher.home", icon: "home", end: true },
  { href: "/teacher/homeroom", label: "Мой класс", icon: "users" },
  { href: "/teacher/classes", labelKey: "nav.teacher.classes", icon: "book" },
  { href: "/teacher/schedule", labelKey: "nav.teacher.schedule", icon: "calendar" },
  { href: "/teacher/assignments", labelKey: "nav.teacher.assignments", icon: "clipboard" },
  { href: "/teacher/exams", labelKey: "nav.teacher.exams", icon: "academic" },
  { href: "/teacher/quizzes", labelKey: "nav.teacher.quizzes", icon: "quiz" },
  { href: "/teacher/surveys", labelKey: "nav.teacher.surveys", icon: "poll" },
  { href: "/teacher/chat", labelKey: "nav.teacher.chat", icon: "chat" },
  { href: "/teacher/grades", labelKey: "nav.teacher.grades", icon: "star" },
  { href: "/teacher/wiki", labelKey: "nav.teacher.wiki", icon: "book" },
  { href: "/teacher/library", labelKey: "nav.teacher.library", icon: "book" },
  { href: "/teacher/news", label: "Новости", icon: "news" },
  { href: "/teacher/friends", label: "Друзья", icon: "users" },
  { href: "/teacher/stats", labelKey: "nav.teacher.stats", icon: "chart" },
];
